### PR TITLE
Disable logging when stopping the registry since logging during atexit can in some cases raise a 'ValueError: I/O operation on closed file'

### PR DESCRIPTION
**Pull request by jsjeannotte**
Ignore RuntimeError when trying to join() a thread that didn't start yet (to prevent the 'cannot join thread before it is started' error when using the library under multiprocessing module)

### CODE REVIEW

**Comment by jsjeannotte** [comment]
I have more details about how to reproduce this: It's caused by an incorrect combination of using multi-threading with multi-processing and using the unsafe `preexec_fn` parameter when starting a subprocess. The resolution in my case was to use the new `start_new_session=True` instead of `preexec_fn=os.setsid` which achieve the same results, but in a thread safe way. So now I'm thinking that the RuntimeError should still be raised to indicate to the user that they are doing something unsafe? Or do we want to suppress it to reduce the support burden?

**Review by copperlight — COMMENTED** [review]
Since this is the result of an improper combination of two concurrency primitives, I am inclined to keep the exception as it is, but it may be worth adding a note to the README explaining how this condition may occur.

**Comment by jsjeannotte** [comment]
I reverted the RuntimeError ignoring logic. This pull request now handles the logging issue that trigger a ValueError when emitted in Registry.stop().

**Comment by jsjeannotte** [comment]
@copperlight This is ready to review.

**Pull request closed without merging**
